[general]
working_directory = "/mnt/workspace"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
style = { shape = "Beam", blinking = "Never" }

[terminal.shell]
program = "/bin/zsh"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Enter"
mods = "Control|Shift"
action = "CreateNewWindow"

[font]
size = 12.0

[font.normal]
family = "Google Sans Code"
style = "Regular"

[font.bold]
family = "Google Sans Code"
style = "SemiBold"

[font.italic]
family = "Google Sans Code"
style = "Italic"

[font.bold_italic]
family = "Google Sans Code"
style = "SemiBold Italic"

# [font.offset]
# x = 0
# y = 1

